name: cwchocolate
favicon: null
layout_spectrum: 0.62417
typography_spectrum: 0.76625
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#76a4c6'
    - '#1a0d05'
    - '#7b5026'
    - '#fdf0e0'
    - '#eac695'
  brandStrength: 0.8125
  lightness: 0.8572274700272828
  saturation: 0.3143928307108581
  rhythmicContrast: 0.12567321001552045
purpose: []
